global:
  scrape_interval:     10s
  external_labels:
    monitor: hello-observability

scrape_configs:
  - job_name: service-1
    scrape_interval: 10s
    static_configs:
      - targets: [service-1:8070]
      
  - job_name: service-2
    scrape_interval: 10s
    static_configs:
      - targets: [service-2:8071]

  - job_name: loki
    scrape_interval: 10s
    static_configs:
      - targets: [loki:3100]

  - job_name: tempo
    scrape_interval: 10s
    static_configs:
      - targets: [tempo:3200]